Доработано приложение по ТЗ 16
Artem-lvv/java-shareit pull request #3
Opened 2024-08-02 20:40 UTC by Artem-lvv

2024-08-03 07:04 UTC, VadimZharkov commented on gateway/src/main/java/ru/pracicum/shareit/booking/BookingClient.java
> +@Service
В данном случае лучше пометить `@Component`, т.к. за `@Service` закреплена определенная смысловая нагрузка (для классов с бизнес-логикой).  Хотя технически обе аннотации по сути одно и тоже делают.

2024-08-03 07:20 UTC, VadimZharkov reviewed
В gateway нужно добавить ErrorHandler для обработки ошибок связанных с валидацией

2024-08-03 07:23 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/ItemRequest/ItemRequestController.java
> +package ru.practicum.shareit.ItemRequest;
В джаве пакеты принято называть маленькими буквами

2024-08-03 07:24 UTC, VadimZharkov commented on server/src/main/java/ru/practicum/shareit/ItemRequest/ItemRequestController.java
> +    public ItemRequestDto createItemRequest(@Valid @RequestBody CreateItemRequestDto createItemRequestDto,
`@Valid `из сервера нужно убрать, сейчас это зона ответственности gateway

2024-08-03 07:29 UTC, VadimZharkov requested changes
Нужно исправить замечания и добиться, чтобы тесты в гите проходили

2024-08-04 14:17 UTC, Artem-lvv commented on gateway/src/main/java/ru/pracicum/shareit/booking/BookingClient.java
> +@Service
Скорректировал аннотацию во всех классах Client

2024-08-04 14:18 UTC, Artem-lvv commented
> В gateway нужно добавить ErrorHandler для обработки ошибок связанных с валидацией

Добавил

2024-08-04 14:18 UTC, Artem-lvv commented on server/src/main/java/ru/practicum/shareit/ItemRequest/ItemRequestController.java
> +package ru.practicum.shareit.ItemRequest;
Изменил наименование пакета

2024-08-04 14:19 UTC, Artem-lvv commented on server/src/main/java/ru/practicum/shareit/ItemRequest/ItemRequestController.java
> +    public ItemRequestDto createItemRequest(@Valid @RequestBody CreateItemRequestDto createItemRequestDto,
Скорректировал

2024-08-04 14:19 UTC, Artem-lvv commented
> Нужно исправить замечания и добиться, чтобы тесты в гите проходили

Провел рефакторинг приложения. Тесты в гит тоже пройдены.

2024-08-05 05:52 UTC, VadimZharkov approved these changes

2024-08-06 09:50 UTC, merged